### ISSUE TITLE
Combat log still unable to be moved

### ISSUE THREAD

**Issue by HOUSECLEGANE** [phanx-wow/PhanxChat#28]
If the chat frame is near the bottom and/or left edges of the screen, the combat log is pushed upward and/or to the right, overlapping the chat tabs. Seems like there are some new hardcoded "minimum distance" values in BFA that need to be overridden.

**Comment by Phanx** [comment]
I already fixed this, which is why I closed the ticket. Make sure you have the latest version. If you're still experiencing the same or a similar problem, please provide more details, including exact steps you can follow to reproduce the problem so I can follow the same steps (eg. "log in, right-click the 1st chat tab, click unlock frame, click the 2nd chat tab to select the combat log, click and drag on the chat tab to move the frame") and whether it still happens when all other addons are disabled.
